SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS planetzoo_dlcs;

CREATE TABLE planetzoo_dlcs (
    id TINYINT UNSIGNED PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(32) NOT NULL,
    release_date DATE NOT NULL,
    CONSTRAINT uq_dlcs UNIQUE ( id, name )
);

SET FOREIGN_KEY_CHECKS = 1;